export const LOAD_ALERT_EVENTS_SUCCESS = 'LOAD_ALERT_EVENTS_SUCCESS';

export const SET_DIRECTION_FILTER = 'SET_DIRECTION_FILTER';
export const SET_ALL_DIRECTION_FILTERS = 'SET_ALL_DIRECTION_FILTERS';

export const SET_LINE_FILTER = 'SET_LINE_FILTER';
export const SET_ALL_LINE_FILTERS = 'SET_ALL_LINE_FILTERS';

export const SET_ALERT_FILTER = 'SET_ALERT_FILTER';
export const SET_ALL_ALERT_FILTERS = 'SET_ALL_ALERT_FILTERS';

export const SET_DATETIME_FILTER = 'SET_DATETIME_FILTER';
