"""create tables

Revision ID: a9710c2a76d1
Revises: 
Create Date: 2017-03-29 12:16:41.596153

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import ENUM


# revision identifiers, used by Alembic.
revision = 'a9710c2a76d1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('routes',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('stops',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alert_id', sa.Integer(), nullable=True),
    sa.Column('effect_name', sa.String(length=32), nullable=True),
    sa.Column('effect', sa.String(length=32), nullable=True),
    sa.Column('cause', sa.String(length=64), nullable=True),
    sa.Column('header_text', sa.String(length=256), nullable=True),
    sa.Column('short_header_text', sa.String(length=256), nullable=True),
    sa.Column('severity', sa.String(length=16), nullable=True),
    sa.Column('created_dt', sa.DateTime(), nullable=True),
    sa.Column('last_modified_dt', sa.DateTime(), nullable=True),
    sa.Column('service_effect_text', sa.String(length=256), nullable=True),
    sa.Column('alert_lifecycle', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alert_effect_period',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alert_id', sa.Integer(), nullable=True),
    sa.Column('effect_start', sa.DateTime(), nullable=True),
    sa.Column('effect_end', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], name='alert_effect_period_alert_id_fkey'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alert_affected_services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alert_id', sa.Integer(), nullable=True),
    sa.Column('route_id', sa.String(length=32), nullable=True),
    sa.Column('trip_id', sa.String(length=64), nullable=True),
    sa.Column('trip_name', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], name='alert_affected_services_route_id_fkey'),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], name='alert_affected_services_alert_id_fkey'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alert_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.String(length=64), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('time', sa.Time(), nullable=True),
    sa.Column('day', sa.Integer(), nullable=True),
    sa.Column('route', sa.String(length=32), nullable=True),
    sa.Column('stop', sa.String(length=32), nullable=True),
    sa.Column('direction', sa.Enum('inbound', 'outbound', name='direction'), nullable=True),
    sa.Column('short_name', sa.String(length=64), nullable=True),
    sa.Column('scheduled_departure', sa.DateTime(), nullable=True),
    sa.Column('actual_departure', sa.DateTime(), nullable=True),
    sa.Column('delay', sa.Interval(), nullable=True),
    sa.Column('alert_issued', sa.Boolean(), nullable=True),
    sa.Column('deserves_alert', sa.Boolean(), nullable=True),
    sa.Column('alert_delay', sa.Interval(), nullable=True),
    sa.Column('alert_timely', sa.Boolean(), nullable=True),
    sa.Column('alert_text', sa.String(length=300), nullable=True),
    sa.Column('predicted_delay', sa.Interval(), nullable=True),
    sa.Column('delay_accuracy', sa.Enum('low', 'accurate', 'high', name='delayaccuracy'), nullable=True),
    sa.CheckConstraint('day >= 0 AND day <= 6', name='alert_events_day_check'),
    sa.ForeignKeyConstraint(['route'], ['routes.id'], name='alert_events_routes_fkey'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('alert_affected_services_alert_id_fkey', 'alert_affected_services', type_='foreignkey')
    op.drop_constraint('alert_affected_services_route_id_fkey', 'alert_affected_services', type_='foreignkey')
    op.drop_constraint('alert_effect_period_alert_id_fkey', 'alert_effect_period', type_='foreignkey')
    op.drop_constraint('alert_events_routes_fkey', 'alert_events', type_='foreignkey')
    op.drop_constraint('alert_events_day_check', 'alert_events', type_='check')

    op.drop_table('alert_events')
    op.drop_table('alert_affected_services')
    op.drop_table('alert_effect_period')
    op.drop_table('alerts')
    op.drop_table('stops')
    op.drop_table('routes')

    ENUM(name="delayaccuracy").drop(op.get_bind(), checkfirst=False)
    ENUM(name="direction").drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###
